# Generated by Django 3.1.2 on 2020-12-01 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('submissionDate', models.DateTimeField(auto_now=True, verbose_name='Date Submitted')),
                ('description', models.TextField(verbose_name='Description')),
                ('highPriority', models.BooleanField(default=None, help_text='Is this issue urgent?', verbose_name='High Priority')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submissionDate'],
                'unique_together': {('user', 'title')},
            },
        ),
    ]
