# Generated by Django 3.1.2 on 2020-10-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='isImportant',
        ),
        migrations.AddField(
            model_name='ticket',
            name='highPriority',
            field=models.BooleanField(default=None, verbose_name='high priority'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='name',
            field=models.CharField(default='name', max_length=100, verbose_name='name'),
            preserve_default=False,
        ),
    ]
