# Generated by Django 3.1.2 on 2020-10-26 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0002_auto_20201021_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='submissionDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='date submitted'),
        ),
    ]
