# Generated by Django 3.1.2 on 2020-10-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0003_auto_20201026_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='name',
        ),
        migrations.AddField(
            model_name='ticket',
            name='firstName',
            field=models.CharField(default='Zachary', max_length=100, verbose_name='first name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='lastName',
            field=models.CharField(default='Wauer', max_length=100, verbose_name='last name'),
            preserve_default=False,
        ),
    ]
