# Generated by Django 3.1.2 on 2020-10-29 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0004_auto_20201029_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='contact',
            field=models.EmailField(max_length=200, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='firstName',
            field=models.CharField(max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='highPriority',
            field=models.BooleanField(default=None, verbose_name='High Priority'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='lastName',
            field=models.CharField(max_length=100, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='submissionDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Date Submitted'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
    ]
