# Generated by Django 3.1.2 on 2020-11-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0005_auto_20201029_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='highPriority',
            field=models.BooleanField(default=None, help_text='Is this issue urgent?', verbose_name='High Priority'),
        ),
    ]
